/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.core  // importantísimo
/* 
package com.tudominio.tujuego
*/
import ktx.app.KtxApplicationAdapter
import ktx.app.clearScreen
import ktx.graphics.use
import ktx.log.info
import ktx.assets.disposeSafely
import com.badlogic.gdx.graphics.Texture
import com.badlogic.gdx.graphics.g2d.SpriteBatch

class MiJuego : KtxApplicationAdapter {
    private lateinit var batch: SpriteBatch
    private lateinit var texture: Texture

    override fun create() {
        batch = SpriteBatch()
        texture = Texture("badlogic.jpg")
        info { "Aplicación desktop creada con Kotlin ${KotlinVersion.CURRENT}" }
    }

    override fun render() {
        clearScreen(0.15f, 0.15f, 0.2f)

        batch.use { spriteBatch ->
            spriteBatch.draw(texture, 0f, 0f)
        }
    }

    override fun dispose() {
        batch.disposeSafely()
        texture.disposeSafely()
        info { "Recursos liberados correctamente" }
    }
}
